terraform {
  required_version = ">= 1.0.0"
}

provider "local" {}

resource "null_resource" "provision_vagrant" {

 #Force terraform to run vagrant up
  triggers = {always_run = timestamp()}

  # Create VM using the existing Vagrantfile
  provisioner "local-exec" {
    command = "vagrant up"
    working_dir = "/Users/viviankiioh/Documents/Triuno/Moringa/yolo"
  }

  # Clean up when destroying resources
  provisioner "local-exec" {
    when    = destroy
    command = "vagrant destroy -f"
    working_dir = "/Users/viviankiioh/Documents/Triuno/Moringa/yolo"
  }
}
resource "null_resource" "ssh_config" {
  depends_on = [null_resource.provision_vagrant]

  provisioner "local-exec" {
    command     = "vagrant ssh-config > ${path.module}/vagrant_ssh_config"
    working_dir = "/Users/viviankiioh/Documents/Triuno/Moringa/yolo"
  }
}

# Output the SSH Config File Path ---
output "vagrant_ssh_config_file" {
  value = "${path.module}/vagrant_ssh_config"
  description = "Path to the SSH config file generated by vagrant ssh-config"
}
