services:
  mongo:
    image: mongo:6.0
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    volumes:
      - yolo-mongo-data:/data/db
    networks:
      - yolo-net

  yolo-backend:
    image: vivfifie/yolo:v1.0.0
    container_name: yolo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://yolo-mongo:27017/yolo-db
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - yolo-net

  yolo-client:
    image: vivfifie/yolo-client:v1.1.1
    container_name: yolo-client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://yolo-backend:5000
    depends_on:
      - yolo-backend
    networks:
      - yolo-net

volumes:
  yolo-mongo-data:
    driver: local

networks:
  yolo-net:
    driver: bridge

